### ISSUE TITLE
Create COAL Website

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/capstone-coal.github.io#1] opened 2016-11-04 03:54 UTC
Hi @xiaomei7 please let us know when you have a proposed Website ready for us to use for the project. The Website will display at http://capstone-coal.github.io. Thank you.

**Comment by lewismc** [comment] 2016-11-22 17:37
@xiaomei7 any progress here? Let me know if you need assistance and we can get you going. Thank you.

**Comment by lewismc** [comment] 2016-11-28 19:15
@xiaomei7 thank you for putting up the original project Website... :)

There is a LOT more content and presentation to be added however. Please consider the theme of the project for starters... we are looking into **Coal and Open-pit surface mining impacts on American Lands**, so can you please re-theme the entire site to reflect this?

Some more TODO's
 * please embed the Google Group into the main page and also link to it so people can see our project correspondence.
 * Create a Project blog (non-development/non-technical style) which introduces the project, the aspirations and is easily modifiable for people wishing to add blog entries.
 * Please provide a wiki page on how to edit the Website and what needs to be done to add a blog entry
 * Please link to the primary COAL repository such that people can see our source code development.

Thank you... this Website will be a dynamic resource and I will be asking you almost every week to make changes to it so please be aware of that.
Thank you

**Comment by lewismc** [comment] 2016-11-28 19:15
@heidiaclayton @browtayl @kwhitehall CC for context thanks.

**Comment by ghost** [comment] 2016-12-03 07:10
I added an issue about adding the slideshow or its content to the website:
https://github.com/capstone-coal/coal/issues/13

Edit: I mistakenly filed the issue against the coal repo rather than the website repo. Future issues will be filed correctly.

**Comment by ghost** [comment] 2017-02-04 09:24
In Friday's meeting some desired content for the website was identified **in addition** to what has been mentioned [above](https://github.com/capstone-coal/capstone-coal.github.io/issues/1#issuecomment-263365406):
* Links to our output to date
    * Papers we have written
        * The PDFs are currently in a Google Drive [folder](https://drive.google.com/drive/folders/0B1hXUEnU66LkZnJlNGhTNVR5TVU) and are accessible without login. We may want to host them elsewhere, such as directly in the website repo.
        * Since we will be editing the papers in the next week, I recommend holding off on these until they are updated.
    * Sketches
        * https://github.com/capstone-coal/coal/blob/ef7f1d746a2458c8222c3bb1f7abc78932a8c00e/docs/nn-sketch.pdf
        * https://github.com/capstone-coal/coal/blob/ef7f1d746a2458c8222c3bb1f7abc78932a8c00e/docs/nn-sketch-2.pdf
        * https://github.com/capstone-coal/coal/blob/ef7f1d746a2458c8222c3bb1f7abc78932a8c00e/docs/mineral-training.jpg
        * https://github.com/capstone-coal/coal/blob/ef7f1d746a2458c8222c3bb1f7abc78932a8c00e/docs/mineral-classification.jpg
        * https://github.com/capstone-coal/coal/blob/ef7f1d746a2458c8222c3bb1f7abc78932a8c00e/docs/mining-classification.jpg
        * https://github.com/capstone-coal/coal/blob/ef7f1d746a2458c8222c3bb1f7abc78932a8c00e/docs/mining-correlation.jpg
        * https://github.com/capstone-coal/coal/blob/ef7f1d746a2458c8222c3bb1f7abc78932a8c00e/docs/temporal-correlation.jpg
    * Wiki Pages
        * https://github.com/capstone-coal/coal/wiki
* Blog
    * Sample topics:
        * Announcements
        * Conference Paper
        * Features
        * Updates from AVIRIS, JPL
* Roadmap
    * Question: Can we use the project [board](https://github.com/orgs/capstone-coal/projects/1)?
        * Note: It is currently not publicly accessible
    * Note: [GitHub Releases](https://help.github.com/articles/about-releases/) are a nice way of setting waypoints
* Interactive [Web Application](https://github.com/capstone-coal/coal/issues/21)
    * Currently **blocked** by classification tasks

I am willing to assist if desired.

**Comment by ghost** [comment] 2017-02-10 06:47
@xiaomei7 i like the way you faded the background image. looks great. also the [papers](https://capstone-coal.github.io/class-paper.html) page is looking good.

note that although you moved this issue to "Done" in the project board, it is still open marked as "Open" in GitHub. there are still a few things above that would be good to resolve either in this issue or a new one:
* the wiki homepage link is incorrect
* the slideshow could be incorporated somehow
* we'd like to set up a blog

as usual, let me know if i can be of any assistance. i can always send you a pull request.

good work :+1:

**Comment by xiaomei7** [comment] 2017-02-10 06:53
@browtayl 
I thought the issue is to create the original website skeleton, that is why I moved it; I could move it to other section later.
I know we have to set up a blog. But I'm struggling to find a way since I never use Jekyll before; so I might need a bit more time. I think I might add the sketches today or early tomorrow, though.

Anyway, thanks for the feedback.

**Comment by ghost** [comment] 2017-02-10 07:00
@xiaomei7 no worries, i was noting these things as much for my benefit as for yours. if you would like to close this issue, you can always hit the "Close Issue" button down below. again, good work.

**Closed as completed** 2017-02-10 21:20 UTC
Labels: enhancement, help wanted
